services:
  # 서버 정보 추가

  # MYSQL
  zoom-bit-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zoom_bit
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" , "ping"]
      interval: 5s
      retries: 10

  # Redis
  zoom-bit-cache:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD" , "redis-cli", "ping"]
      interval: 5s
      retries: 10

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zoom-bit-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka
  kafka:
    image: confluentinc/cp-kafka
    container_name: zoom-bit-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql_data:
    driver: local