services:
  # 서버 정보 추가

  # MYSQL
  zoom-bit-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zoom_bit
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" , "ping"]
      interval: 5s
      retries: 10

  # Redis
  zoom-bit-cache:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD" , "redis-cli", "ping"]
      interval: 5s
      retries: 10

  # Zookeeper (모든 Kafka 브로커가 공유)
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  # Kafka Broker 1
  kafka-1:
    image: confluentinc/cp-kafka
    container_name: kafka-1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - kafka-network

  # Kafka Broker 2
  kafka-2:
    image: confluentinc/cp-kafka
    container_name: kafka-2
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    networks:
      - kafka-network

  # Kafka Broker 3
  kafka-3:
    image: confluentinc/cp-kafka
    container_name: kafka-3
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    networks:
      - kafka-network

networks:
  kafka-network:

volumes:
  mysql_data:
    driver: local